In [1]:
import pandas as pd

# Read and clean original outpatient claims file

In [2]:
# import and read outpatient file
outpt_org = "DE1_0_2008_to_2010_Outpatient_Claims_Sample_1.csv"
outpt_df = pd.read_csv(outpt_org)

C:\Users\gorin\Anaconda3\envs\pythondata\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (21,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
# only include data from 2008
newoutpt_df = outpt_df[outpt_df.CLM_FROM_DT <20090101]
newoutpt_df.head()

,DESYNPUF_ID,CLM_ID,SEGMENT,CLM_FROM_DT,CLM_THRU_DT,PRVDR_NUM,CLM_PMT_AMT,NCH_PRMRY_PYR_CLM_PD_AMT,AT_PHYSN_NPI,OP_PHYSN_NPI,...,HCPCS_CD_36,HCPCS_CD_37,HCPCS_CD_38,HCPCS_CD_39,HCPCS_CD_40,HCPCS_CD_41,HCPCS_CD_42,HCPCS_CD_43,HCPCS_CD_44,HCPCS_CD_45
0,00013D2EFD8E45D1,542192281063886,1,20080904.0,20080904.0,2600RA,50.0,0.0,4.824842e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00024B3D2352D2D0,542242281386963,1,20080712.0,20080712.0,5200TV,30.0,0.0,9.688809e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0002F28CE057345B,542162280904893,1,20080423.0,20080423.0,3902NU,10.0,0.0,7.985077e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0002F28CE057345B,542192281407888,1,20080724.0,20080724.0,3902NU,60.0,0.0,4.201755e+08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0002F28CE057345B,542342281460715,1,20080727.0,20080727.0,3900RQ,200.0,0.0,7.535794e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# remove unwanted columns
newoutpt_df = newoutpt_df.drop(["SEGMENT", "CLM_FROM_DT", "CLM_THRU_DT", "PRVDR_NUM", "CLM_PMT_AMT", 
                                "NCH_PRMRY_PYR_CLM_PD_AMT", "AT_PHYSN_NPI", "OP_PHYSN_NPI", "OT_PHYSN_NPI", 
                                "NCH_BENE_BLOOD_DDCTBL_LBLTY_AM", "NCH_BENE_PTB_DDCTBL_AMT", 
                                "NCH_BENE_PTB_COINSRNC_AMT", 
                                "HCPCS_CD_1", "HCPCS_CD_2", "HCPCS_CD_3", "HCPCS_CD_4", "HCPCS_CD_5", 
                                "HCPCS_CD_6", "HCPCS_CD_7", "HCPCS_CD_8", "HCPCS_CD_9", "HCPCS_CD_10",                              
                                "HCPCS_CD_11", "HCPCS_CD_12", "HCPCS_CD_13", "HCPCS_CD_14", "HCPCS_CD_15", 
                                "HCPCS_CD_16", "HCPCS_CD_17", "HCPCS_CD_18", "HCPCS_CD_19", "HCPCS_CD_20", 
                                "HCPCS_CD_21", "HCPCS_CD_22", "HCPCS_CD_23", "HCPCS_CD_24", "HCPCS_CD_25", 
                                "HCPCS_CD_26", "HCPCS_CD_27", "HCPCS_CD_28", "HCPCS_CD_29", "HCPCS_CD_30", 
                                "HCPCS_CD_31", "HCPCS_CD_32", "HCPCS_CD_33", "HCPCS_CD_34", "HCPCS_CD_35", 
                                "HCPCS_CD_36", "HCPCS_CD_37", "HCPCS_CD_38", "HCPCS_CD_39", "HCPCS_CD_40",
                                "HCPCS_CD_41", "HCPCS_CD_42", "HCPCS_CD_43", "HCPCS_CD_44", "HCPCS_CD_45"], axis=1)
newoutpt_df.head()

,DESYNPUF_ID,CLM_ID,ICD9_DGNS_CD_1,ICD9_DGNS_CD_2,ICD9_DGNS_CD_3,ICD9_DGNS_CD_4,ICD9_DGNS_CD_5,ICD9_DGNS_CD_6,ICD9_DGNS_CD_7,ICD9_DGNS_CD_8,ICD9_DGNS_CD_9,ICD9_DGNS_CD_10,ICD9_PRCDR_CD_1,ICD9_PRCDR_CD_2,ICD9_PRCDR_CD_3,ICD9_PRCDR_CD_4,ICD9_PRCDR_CD_5,ICD9_PRCDR_CD_6,ADMTNG_ICD9_DGNS_CD
0,00013D2EFD8E45D1,542192281063886,V5841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,V5883
4,00024B3D2352D2D0,542242281386963,6009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60021
9,0002F28CE057345B,542162280904893,7902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25000
10,0002F28CE057345B,542192281407888,7232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7202
11,0002F28CE057345B,542342281460715,25012,V5867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25002

In [5]:
# make each ICD9 code a new row instead of a new column
df = newoutpt_df
df = df.rename(columns = {"ICD9_DGNS_CD_1":"DG",
                         "ICD9_DGNS_CD_2":"DG", "ICD9_DGNS_CD_3":"DG", "ICD9_DGNS_CD_4":"DG", "ICD9_DGNS_CD_5":"DG", "ICD9_DGNS_CD_6":"DG", "ICD9_DGNS_CD_7":"DG", "ICD9_DGNS_CD_8":"DG", "ICD9_DGNS_CD_9":"DG", "ICD9_DGNS_CD_10":"DG"}) 

df1 = df.iloc[:, [0, 1, 2, 18]]
df2 = df.iloc[:, [0, 1, 3, 18]]
df3 = df.iloc[:, [0, 1, 4, 18]]
df4 = df.iloc[:, [0, 1, 5, 18]]
df5 = df.iloc[:, [0, 1, 6, 18]]
df6 = df.iloc[:, [0, 1, 7, 18]]
df7 = df.iloc[:, [0, 1, 8, 18]]
df8 = df.iloc[:, [0, 1, 9, 18]]
df9 = df.iloc[:, [0, 1, 10, 18]]
df = [df1, df2, df3, df4, df5, df6, df7, df8, df9]
df = pd.concat(df)

In [6]:
# add a column to note that these diagnosis are from outpatient claims 
df['type'] = 'outpatient'
df.head()

         DESYNPUF_ID           CLM_ID     DG ADMTNG_ICD9_DGNS_CD        type
0   00013D2EFD8E45D1  542192281063886  V5841               V5883  outpatient
4   00024B3D2352D2D0  542242281386963   6009               60021  outpatient
9   0002F28CE057345B  542162280904893   7902               25000  outpatient
10  0002F28CE057345B  542192281407888   7232                7202  outpatient
11  0002F28CE057345B  542342281460715  25012               25002  outpatient

In [7]:
# drop duplicate ICD 9 Codes for each patient
df.drop_duplicates()
#from 283208 rows Ã— 76 columns to 1009174 rows Ã— 5 columns

,DESYNPUF_ID,CLM_ID,DG,ADMTNG_ICD9_DGNS_CD,type
0,00013D2EFD8E45D1,542192281063886,V5841,V5883,outpatient
4,00024B3D2352D2D0,542242281386963,6009,60021,outpatient
9,0002F28CE057345B,542162280904893,7902,25000,outpatient
10,0002F28CE057345B,542192281407888,7232,7202,outpatient
11,0002F28CE057345B,542342281460715,25012,25002,outpatient
...,...,...,...,...,...
790515,FFEC9A4A8E0DA060,542522281394021,NaN,NaN,outpatient
790547,FFF01DD56E7A7717,542242281035346,V140,462,outpatient
790557,FFF1A741EFDC4507,542032281622736,5533,NaN,outpatient
790558,FFF1A741EFDC4507,542672281082059,V1005,NaN,outpatient
790665,FFF9564A4E674C72,542682280995198,NaN,NaN,outpatient

In [8]:
# write to csv
df.to_csv("NewOutpt.csv", index=False, header=True)